owner: umarhadi
repo: upptime

sites:
  - name: umarhadi.dev
    url: https://umarhadi.dev
  - name: Mastodon
    url: https://kawakawa.fun
  - name: Pixelfed
    url: https://pixelfed.kawakawa.fun

assignees:
  - umarhadi

status-website:
  cname: status.umarhadi.dev
  apiBaseUrl: https://api.github.com
  logoUrl: https://avatars.githubusercontent.com/u/31447862?v=4
  name: Very Upptime
  introTitle: "Very status page monitoring for my services and services I use"
  navbar:
    - title: Status
      href: /
    - title: Contact
      href: https://umarhadi.dev/contact
    - title: GitHub
      href: https://github.com/$OWNER/$REPO